"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

user.name = "T6"
user.email = "t6@t6.fyi"

ui.default-command = "log"
ui.always-allow-large-revsets = true

aliases.preprompt = ["log"]

templates.log = "log"
revsets.log = "log"
revset-aliases.log = "subgraph(log_heads)"
revset-aliases.log_heads = "(@ | trunk()---- | bookmarks() | (visible_heads() ~ remote_bookmarks() ~ tags())) ~ ignore() ~ stashed()::"

revset-aliases.'immutable_heads()' = 'present(trunk()) | tags()'

aliases.cm = ["commit", "-m"]
aliases.dm = ["desc", "-m"]
aliases.bs = ["bookmark", "set", "-B", "-r"]
aliases.bp = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]
aliases.bc = ["bookmark", "create", "-r", "@-"]
aliases.ab = ["abandon"]
aliases.re = ["rebase"]
aliases.l = ["log", "-r"]
aliases.h = ["log", "-r", "::@"]
aliases.push = ["git", "push"]
aliases.fetch = ["git", "fetch"]
aliases.log-full = ["log", "-T", "builtin_log_compact"]
