"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

aliases.alias = ["config-grep", "aliases"]
aliases.aliasr = ["config-grep", "revset-aliases"]
aliases.aliast = ["config-grep", "template-aliases"]
aliases.aliasc = ["config-grep", "colors"]

aliases.config-grep = ["bash", "result=`jj config-grep-inner \"${1}\" \"${2}\"`; [[ -n $result ]] && echo $result || jj config-grep-inner \"${1}\" \"${2}.*?\""]
aliases.config-grep-inner = ["bash", "jj config list \"$1\" | rg -P \"^${1}\\\\.([\\\"]?)${2}\\\\1(?= = )\" --color=always | sort"]
