"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

revset-aliases.'private()' = 'anon() ~ root()'
revset-aliases.'push_head(x)' = 'fork_point(heads(::x- ~ private()::))'

aliases.push = ["bash", '''
for bookmark in `jj revset-bookmarks "${@:-@::}"`; do
  if [[ -z `jj bookmark list --tracked $bookmark` ]]; then
    if [[ `jj config get git.sign-on-push` -eq 'true' ]]; then
      echo "Signing..."
      jj sign -r "::push_head($bookmark) & mutable() & mine() ~ signed()"
    fi
    push_head=`jj revset-commit "push_head($bookmark)"`
    if [[ -n "$push_head" ]]; then
      git push -f origin "$push_head:refs/heads/$bookmark"
    fi
  fi
done
''']

aliases.finalize = ["transaction", "bash", '''
IFS="|"
jj rebase -r "reachable($*, main..) ~ ::($*)" -d main
jj abandon "main..($*)"
''']
