"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

revset-aliases.'private()' = 'anon() ~ root()'
revset-aliases.'push_head(x)' = 'latest(heads(::x- ~ private()::))'

aliases.push = ["bash", '''
for bookmark in `jj revset-bookmarks "${@:-@::}"`; do
  if [[ -z `jj bookmark list --tracked $bookmark` ]]; then
    push_head=`jj revset-commit "push_head($bookmark)"`
    if [[ -n "$push_head" ]]; then
      git push -f origin "$push_head:refs/heads/$bookmark"
    fi
  fi
done
''']
