"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

revset-aliases.'private()' = 'anon() ~ root()'
revset-aliases.'push_head(x)' = 'fork_point(heads(::x- ~ private()::))'

aliases.push = ["bash", '''
for bookmark in `jj revset-bookmarks "${@:-@::}"`; do
  if [[ -z `jj bookmark list --tracked $bookmark` ]]; then
    push_head=`jj revset-commit "push_head($bookmark)"`
    if [[ -n "$push_head" ]]; then
      git push -f origin "$push_head:refs/heads/$bookmark"
    fi
  fi
done
''']

revset-aliases.'push_finalize_base()' = "default()"

aliases.finalize = ["transaction", "bash", '''
IFS="|"
revset="${*:-'none()'}"
base='push_finalize_base()'
jj revset-commit "$revset" &>/dev/null || { echo "Error re revset '$revset'"; exit 1; }
jj revset-commit "$base" &>/dev/null || { echo "Error re revset 'push_finalize_base()'"; exit 1; }
jj rebase -r "reachable($*, ($base)..) ~ ::($revset)" -d "${base}"
jj abandon "($base)..($revset)"
jj simplify-parents
''']
