"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

aliases.stash = ["new", "--no-edit", "-m", "@stash"]
aliases.stashed = ["log", "--no-graph", "-r", "stashed()"]
aliases.unstash = ["bash", 'jj abandon "stashing($1)"']

revset-aliases.'stasher()' = 'description("@stash")'
revset-aliases.'stashed()' = 'stasher()-'
revset-aliases.'stashing(x)' = 'x+ & stasher()'
