"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

user.name = "vjjft"
user.email = "vjjft@vjjft.com"

ui.default-command = "log"
ui.movement.edit = true

revset-aliases.'private()' = "anon() ~ root() | @ | description(glob:'wip:*') | description(glob:'private:*')"
git.private-commits = "private()::"

aliases.preprompt = ["log"]

templates.log = "log"
revsets.log = "log"
revset-aliases.log = "subgraph(log_heads)"
revset-aliases.log_heads = "(@ | trunk() | bookmarks() | (visible_heads() ~ remote_bookmarks() ~ tags())) ~ ignore() ~ stashed()::"

revset-aliases.'default()' = "dev"

aliases.cm = ["commit", "-m"]
revset-aliases.'bookmarked(r)' = "r & bookmarks()"
revset-aliases.'prev_bookmarked(r)' = "heads(bookmarked(r))"
revset-aliases.'earlier_bookmarked(r)' = "fork_point(bookmarked(r)) & ~prev_bookmarked(r)"
revset-aliases.'next_bookmarked(r)' = "fork_point(bookmarked(r))"
revset-aliases.'later_bookmarked(r)' = "heads(bookmarked(r)) & ~next_bookmarked(r)"

aliases.ae = ["bash", "R=\"${1:-@}\"; jj ax \"empty() & anon() & ~bookmarks() & ($R)\";"]
aliases.aen = ["ae", "@+"]
aliases.aep = ["ae", "@-"]
aliases.ad = ["bash", "R=\"${1:-@}\"; jj ax \"empty() & ~bookmarks() & ($R)\";"]
aliases.adn = ["ad", "@+"]
aliases.adp = ["ad", "@-"]
aliases.ax = ["transaction", "bash", "R=\"${1:-@}\"; jj abandon -r \"$R\" && { [[ $R = '@' ]] && jj edit @- || true; };"]
aliases.axn = ["ax", "@+"]
aliases.axp = ["ax", "@-"]
aliases.cnote = ["bash", "jj new -B @ --no-edit -m \"// $@\""]
aliases.de = ["desc"]
aliases.den = ["desc", "-r @+"]
aliases.dep = ["desc", "-r @-"]
aliases.dm = ["desc", "-m"]
aliases.bs = ["bookmark", "set", "-B", "-r"]
aliases.bp = [ "bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-", ]
aliases.bc = ["bookmark", "create", "-r", "@-"]
aliases.ab = ["abandon"]
aliases.re = ["rebase"]
aliases.l = ["log", "-r"]
aliases.h = ["log", "-r", "::@"]
aliases.pu = ["push"]
aliases.fetch = ["git", "fetch"]
aliases.f = ["fetch"]
aliases.log-full = ["log", "-T", "builtin_log_compact"]

aliases.c = ["split"]
aliases.ca = ["c","all()"]
aliases.cam = ["bash", "jj ca -m \"$*\""]
# aliases.cam = ["bash","jj split -m \"$@\""]

aliases.xx = ["op","restore"]
aliases.z = ["undo"]

aliases.e = ["edit"]
aliases.en = ["next", "-e"]
aliases.enc = ["en", "--conflict"]
aliases.ep = ["prev", "-e"]
aliases.epc = ["ep", "--conflict"]

aliases.n = ["new", "-A @"]
aliases.np = ["new", "-B @"]

aliases.d = ["diff", "--stat"]
aliases.dn = ["d", "-r @+"]
aliases.dp = ["d", "-r @-"]

aliases.dd = ["diff"]
aliases.ddn = ["dd", "-r @+"]
aliases.ddp = ["dd", "-r @-"]

aliases.s = ["show", "--stat"]
aliases.sn = ["s","@+"]
aliases.sp = ["s","@-"]

aliases.ss = ["show"]
aliases.ssn = ["ss","@+"]
aliases.ssp = ["ss","@-"]

aliases.q = ["squash","--keep-emptied"]
aliases.qi = ["q","-i"]
aliases.qn = ["squash","-r @+"]
aliases.qni = ["qn","-i"]
aliases.qp = ["squash","-r @-"]
aliases.qpi = ["qp","-i"]

aliases.hd = ["log", "-r", "dev::@", "--reversed"]
aliases.ri = ["restore", "-i"]

aliases.prc = ["bash", "gh pr create -H `jj bn`"]

aliases.sync = ["bash", "jj @ ${@:-live} up"]
aliases.wip = ["bash", "jj dm \"wip: ${*}\""]

aliases.bn = [ "log", "-r", "heads(::@ & bookmarks())", "-T", "bn_local", "--no-graph", ]
template-aliases.'bn_local' = "self.local_bookmarks().map(|x| x.name())"

revset-aliases.log_builds = "up_to((@ | bookmarks() | (visible_heads() ~ remote_bookmarks() ~ tags()) | latest_builds) ~ ignore ~ stashed)"
revset-aliases.build_tag = 'tags(regex:"^v")'
revset-aliases.latest_builds = 'build_tag ~ (::build_tag--)+'
revset-aliases.'immutable_heads()' = 'present(trunk()) | tags()'
revset-aliases.'p' = '@-'
revset-aliases.'p(n)' = 'roots(ancestors(@, n))'
revset-aliases.'p(r, n)' = 'roots(ancestors(r, n))'
revset-aliases.tip = 'heads(@::)'
revset-aliases._prev_bm = "_prev_bm(@)"
revset-aliases.'_prev_bm(r)' = "heads(::r & bookmarks())"
